# This program will calculate the commission generated by the workers of an enterprise
# that is a %13 of the total value of their sucessful sales

employee = input("Insert employee name: ")
sales_total_value = float(input("Insert the total value of the employee sucessful sales: "))

print(f"The comission generated by {employee} are {round(sales_total_value * 0.13,3)}$, congratulations!")



